import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import SocialConnect from '@/dependencies/components/socialComponent/socialConnect'
import NavBar from '@/dependencies/components/NavBar/NavBar'
import Footer from '@/dependencies/components/Footer'

const inter = Inter({ subsets: ['latin'] })

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {children}
        <SocialConnect />
        <Footer />
        <NavBar />
      </body>
    </html>
  )
}
